import Head from "next/head";
import { Bodoni_Moda } from "@next/font/google";
import {
  Header,
  Hero,
  MultiCarousel,
  Section,
  Collection,
  Footer,
} from "../components";
import image4 from "../public/images/img4.jpg";
import image7 from "../public/images/img7.jpg";
import image8 from "../public/images/img8.jpg";
import image3 from "../public/images/img3.jpg";
import image5 from "../public/images/img5.jpg";
import image14 from "../public/images/img14.jpg";
import image17 from "../public/images/img17.jpg";
import image18 from "../public/images/img18.jpg";
import image19 from "../public/images/img19.jpg";
import image20 from "../public/images/img20.jpg";

const inter = Bodoni_Moda({ subsets: ["latin"] });

const imageSet = [image4, image7, image8, image3, image5];
const imageSet2 = [image17, image18, image19, image20, image14];

export default function Home() {
  return (
    <>
      <Head>
        <title>Fevrier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <Hero />
        <Section title={"Shop the Spring Collection"} />
        <MultiCarousel images={imageSet} />
        <Collection />
        <Section title={"Fall-winter collection 2022"} />
        <MultiCarousel images={imageSet2} />
        <Footer />
      </main>
    </>
  );
}
