import Head from "next/head";
import { Bodoni_Moda } from "@next/font/google";
import { Header, Hero } from "../components";

const inter = Bodoni_Moda({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Fevrier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Header />
        <Hero />
      </main>
    </>
  );
}
